project:
  type: website

website:
  title: "Portifolio"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Arthur Rodrigues
      - text: Works
        menu:
          - shiny.qmd
  page-footer:
    left: "Created with [Quarto](https://quarto.org) by [Arthur Rodrigues](https://github.com/avrodrigues)."
    right:
      - icon: github
        href: https://github.com/avrodrigues
      - icon: twitter
        href: https://twitter.com/avrodrigues_
      - icon: linkedin
        href: https://www.linkedin.com/in/avrodrigues/


format:
  html:
    theme:
      light: flatly
      dark: darkly
    link-external-icon: false
    link-external-newwindow: true
    css: styles.css
    toc: true
    mainfont: 'Source Sans Pro'


execute:
  freeze: auto
